package com.yiyuplatform.entity;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hibernate.annotations.DynamicInsert;

import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: 2021-12-08 22:26:37.</p>
 *
 * @author custom
 */

@Table ( name ="chat_t_contact" )
@Data
@ApiModel
@Entity
@DynamicInsert
public class ChatTContact implements Serializable {
	private static final long serialVersionUID =  5738996369154371554L;

	/**
	 * 聊天会话的session_key
	 */
   	@Column(name = "CHAT_SESSIONKEY" )
	@ApiModelProperty( value="聊天会话的session_key")
	@Id
	private String chatSessionkey;

	/**
	 * 聊天人一的uuid
	 */
	@Column(name = "CHAT_ME_ID" )
	@ApiModelProperty( value="聊天人一的uuid")
	private String chatMeId;

	/**
	 * 聊天人二的uuid
	 */
	@Column(name = "CHAT_FRD_ID" )
	@ApiModelProperty( value="聊天人二的uuid")
	private String chatFrdId;

	/**
	 * 最近一条消息
	 */
   	@Column(name = "CHAT_LAST_MESSAGE" )
	@ApiModelProperty( value="最近一条消息")
	private String chatLastMessage;

	/**
	 * 最近发消息时间
	 */
   	@Column(name = "CHAT_LAST_TIME" )
	@ApiModelProperty( value="最近发消息时间")
	private Date chatLastTime;

}
