version: '3'

services:
  nginx: # 服务名称
    image: nginx:latest
    ports:
      - 80:80
    volumes: # 挂载
    - /root/nginx.nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=sqladmin
  redis:
    image: redis:latest
  yiyuplatform:
    image: yiyuplatform:latest
    build: .
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - redis
